// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_4xk1OlAYFdBdZ2sYA1nza3hxVGNNSjg',
    appId: '1:635939585363:web:e4ea89e96091d265f435a6',
    messagingSenderId: '635939585363',
    projectId: 'hiredorm-5d045',
    authDomain: 'hiredorm-5d045.firebaseapp.com',
    storageBucket: 'hiredorm-5d045.appspot.com',
    measurementId: 'G-9DT0D5ESJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKkij9snOpk2-7IjyVjvM8-jmMl3WrkdQ',
    appId: '1:635939585363:android:897ef022200c545bf435a6',
    messagingSenderId: '635939585363',
    projectId: 'hiredorm-5d045',
    storageBucket: 'hiredorm-5d045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiRxDIoVoXrcT5x0ButWp_3PmcoRVgjAs',
    appId: '1:635939585363:ios:8f231b83210c8ca4f435a6',
    messagingSenderId: '635939585363',
    projectId: 'hiredorm-5d045',
    storageBucket: 'hiredorm-5d045.appspot.com',
    iosClientId: '635939585363-a3k27os4f0mblef9mf35r4o932eefsgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.hireDorm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiRxDIoVoXrcT5x0ButWp_3PmcoRVgjAs',
    appId: '1:635939585363:ios:d19a7e9001734161f435a6',
    messagingSenderId: '635939585363',
    projectId: 'hiredorm-5d045',
    storageBucket: 'hiredorm-5d045.appspot.com',
    iosClientId: '635939585363-om1tgp1pkl0hhknfl38j9k9ctsujluus.apps.googleusercontent.com',
    iosBundleId: 'com.example.hireDorm.RunnerTests',
  );
}